spring:
  application:
    name: rest-with-spring-boot-and-java
    datasource:
      driver-class-name: com.mysql.cj.jdbc.driver
      url: jdbc:mysql://localhost:3306/rest_with_spring_boot_and_java?userTimezone=true&serverTimezone=UTC
      username: root
      password: root
      

